src/main/java/ru/bsu/coacher/entities/Account.java
package ru.bsu.coacher.entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import ru.bsu.coacher.shared.Gender;
import ru.bsu.coacher.shared.AccountData;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class Account implements Serializable, AccountData {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date registered;
    
    @Column(nullable = false)
    private Boolean approvedEmail;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date lockedUntil;
    
    @Column(nullable = false)
    private String passwordHash;
    
    @ManyToMany
    private final Collection<Role> roles = new ArrayList<>();
    
    @Column(unique = true, nullable = false)
    private String email;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "account")
    private final Collection<OneTimeToken> oneTimeTokens = new ArrayList<>();
    
        @OneToMany(mappedBy = "owner")
    private final List<DialogItem> dialogItems = new ArrayList<>();
    
    @Enumerated(javax.persistence.EnumType.STRING)
    private Gender gender;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date birthDate;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date created;
    
    private String workplace;
    private String occupation;
    
    private String phone;
    
    private String lastName;
    private String firstName;
    private String middleName;

    public List<DialogItem> getDialogItems() {
        return dialogItems;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }
    
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getWorkplace() {
        return workplace;
    }

    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }

    public String getOccupation() {
        return occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    public String getFullFIO() {
        if (lastName == null && firstName == null && middleName == null) {
            return "Безымянный #" + getId();
        }
        return lastName + " " + firstName + " " + middleName;
    }
    
    public String getShortFIO() {
        if (lastName == null && firstName == null && middleName == null) {
            return "Безымянный #" + getId();
        }
        return 
                (firstName == null ? "" : firstName.substring(0, 1) + ". ") +
                (middleName == null ? "" : middleName.substring(0, 1) + ". ") +
                lastName;
    }

    public Collection<OneTimeToken> getOneTimeTokens() {
        return oneTimeTokens;
    }

    public Collection<Role> getRoles() {
        return roles;
    }
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getRegistered() {
        return registered;
    }

    public void setRegistered(Date registered) {
        this.registered = registered;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    
    public boolean hasRole(String role) {
        for (Role r : roles) {
            if (r.getId().equals(role)) {
                return true;
            }
        }
        return false;
    }

    public Boolean getApprovedEmail() {
        return approvedEmail;
    }

    public void setApprovedEmail(Boolean approved) {
        this.approvedEmail = approved;
    }

    public Date getLockedUntil() {
        return lockedUntil;
    }

    public void setLockedUntil(Date lockedUntil) {
        this.lockedUntil = lockedUntil;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Account)) {
            return false;
        }
        Account other = (Account) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ru.bsu.coacher.Account[ id=" + id + " ]";
    }
}

src/main/java/ru/bsu/coacher/entities/Athlete.java

package ru.bsu.coacher.entities;

import ru.bsu.coacher.shared.SportDegree;
import ru.bsu.coacher.shared.LivingPlace;
import ru.bsu.coacher.shared.FamilyStatus;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import ru.bsu.coacher.entities.records.RecordValue;
import ru.bsu.coacher.shared.AthleteData;

@Entity
public class Athlete extends Account implements AthleteData {
    private String birthPlace;
    private String nationality;
    private String religion;
    private String studyPlace;
    private float height;
    private float weight;
    private String sport;
    @Enumerated(javax.persistence.EnumType.STRING)
    private SportDegree sportDegree;
    private int parents;
    @Enumerated(javax.persistence.EnumType.STRING)
    private LivingPlace livingPlace;
    private String livingAddress;
    @Enumerated(javax.persistence.EnumType.STRING)
    private FamilyStatus familyStatus;
    private int children;
    private String diseases;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "athlete")
    private final Collection<CompetitionResult> competitionResults = new ArrayList<>();
    
    @OneToMany(cascade = CascadeType.ALL)
    private final List<RecordValue> records = new ArrayList<>();
    
    @ManyToMany(mappedBy = "attachedAthletes")
    private final List<Master> masters = new ArrayList<>();

    public List<Master> getMasters() {
        return masters;
    }
    
    public Coach getCoach() {
        Coach coach = null;
        for (Master master : masters) {
            if (master instanceof Coach) {
                coach = (Coach)master;
                break;
            }
        }
        return coach;
    }
    
    public void setCoach(Coach coach) {
        Coach existingCoach = getCoach();
        if (existingCoach != null)
            if (!masters.remove(existingCoach))
                throw new IllegalStateException();
        masters.add(coach);
    }

    @Override
    public String getBirthPlace() {
        return birthPlace;
    }

    @Override
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    @Override
    public String getNationality() {
        return nationality;
    }

    @Override
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Override
    public String getReligion() {
        return religion;
    }

    @Override
    public void setReligion(String religion) {
        this.religion = religion;
    }

    @Override
    public String getStudyPlace() {
        return studyPlace;
    }

    @Override
    public void setStudyPlace(String studyPlace) {
        this.studyPlace = studyPlace;
    }

    @Override
    public float getHeight() {
        return height;
    }

    @Override
    public void setHeight(float height) {
        this.height = height;
    }

    @Override
    public float getWeight() {
        return weight;
    }

    @Override
    public void setWeight(float weight) {
        this.weight = weight;
    }

    @Override
    public String getSport() {
        return sport;
    }

    @Override
    public void setSport(String sport) {
        this.sport = sport;
    }

    @Override
    public SportDegree getSportDegree() {
        return sportDegree;
    }

    @Override
    public void setSportDegree(SportDegree sportDegree) {
        this.sportDegree = sportDegree;
    }

    @Override
    public int getParents() {
        return parents;
    }

    @Override
    public void setParents(int parents) {
        this.parents = parents;
    }

    @Override
    public LivingPlace getLivingPlace() {
        return livingPlace;
    }

    @Override
    public void setLivingPlace(LivingPlace livingPlace) {
        this.livingPlace = livingPlace;
    }

    @Override
    public String getLivingAddress() {
        return livingAddress;
    }

    @Override
    public void setLivingAddress(String livingAddress) {
        this.livingAddress = livingAddress;
    }

    @Override
    public FamilyStatus getFamilyStatus() {
        return familyStatus;
    }

    @Override
    public void setFamilyStatus(FamilyStatus familyStatus) {
        this.familyStatus = familyStatus;
    }

    @Override
    public int getChildren() {
        return children;
    }

    @Override
    public void setChildren(int children) {
        this.children = children;
    }

    @Override
    public String getDiseases() {
        return diseases;
    }

    @Override
    public void setDiseases(String diseases) {
        this.diseases = diseases;
    }
    
    public List<RecordValue> getRecords() {
        return records;
    }

    public Collection<CompetitionResult> getCompetitionResults() {
        return competitionResults;
    }
}

src/main/java/ru/bsu/coacher/entities/Master.java
package ru.bsu.coacher.entities;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

@Entity
public abstract class Master extends Account {
    @ManyToMany
    @JoinTable(name = "master_athletes",
            joinColumns = {
                @JoinColumn(name = "master_id", nullable = false, updatable = false)
            },
            inverseJoinColumns = {
                @JoinColumn(name = "athlete_id", nullable = false, updatable = false)
            })
    private final List<Athlete> attachedAthletes = new ArrayList<>();
    
    @OneToMany(mappedBy = "master", cascade = CascadeType.ALL)
    private final Collection<AthleteRequest> requests = new ArrayList<>();

    public List<Athlete> getAttachedAthletes() {
        return attachedAthletes;
    }

    public Collection<AthleteRequest> getRequests() {
        return requests;
    }
}

src/main/java/ru/bsu/coacher/entities/records/RecordValue.java
package ru.bsu.coacher.entities.records;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import ru.bsu.coacher.entities.Account;
import ru.bsu.coacher.entities.Athlete;
import ru.bsu.coacher.shared.RecordValueType;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class RecordValue implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @ManyToOne
    private Record record;
    
    @ManyToOne
    private Athlete athlete;
    
    @ManyToOne
    private Account author;
    
    @Temporal(TemporalType.DATE)
    private Date day;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date added;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date updated;
    
    private String comment;

    public Date getDay() {
        return day;
    }

    public void setDay(Date day) {
        this.day = day;
    }

    public Record getRecord() {
        return record;
    }

    public void setRecord(Record record) {
        this.record = record;
    }

    public Athlete getAthlete() {
        return athlete;
    }

    public void setAthlete(Athlete athlete) {
        this.athlete = athlete;
    }

    public Account getAuthor() {
        return author;
    }

    public void setAuthor(Account author) {
        this.author = author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getAdded() {
        return added;
    }

    public void setAdded(Date added) {
        this.added = added;
    }

    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof RecordValue)) {
            return false;
        }
        RecordValue other = (RecordValue) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ru.bsu.coacher.RecordValue[ id=" + id + " ]";
    }

    public abstract RecordValueType getValueType();
}

src/main/webapp/cabinet/add_record.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <ui:composition template="/WEB-INF/faces/layout_cabinet.xhtml">
            <ui:define name="content">
                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/cabinet/dialogs.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:body>
        <ui:composition template="/WEB-INF/faces/layout_cabinet.xhtml">
            <ui:define name="header">Сообщения</ui:define>
            <ui:define name="content">
                <div class="container">
                    <div class="row" style="background-color: #e9e9e9; padding: 1em 0em; border-radius: 4px">
                        <div class="col-xs-12">
                            <form class="form-inline" method="get" action="dialog.xhtml">
                                <select class="form-control" name="id">
                                    <ui:repeat value="#{dialogs.availableReceivers}" var="r">
                                        <option value="#{r.id}">#{r.fullFIO}</option>
                                    </ui:repeat>
                                </select>
                                <button class="btn btn-default" style="margin-right: 1em">
                                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                                    Перейти к диалогу
                                </button>
                            </form>
                        </div>
                    </div>
                    <hr />
                    <ui:repeat value="#{dialogs.lastMessages}" var="lm">
                        <div class="row">
                            <div class="col-xs-12">
                                <a href="dialog.xhtml?id=#{lm.accountId}">
                                    #{lm.accountName} <span class="badge">(#{lm.totalUnread} не прочитано)</span>
                                </a>
                            </div>
                        </div>
                    </ui:repeat>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/cabinet/edit_records.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <f:metadata>
            <f:viewParam name="group" value="#{cabinetRecords.groupId}" />
            <f:event type="preRenderComponent" listener="#{cabinetRecords.init()}"/>
        </f:metadata>
        <ui:composition template="/WEB-INF/faces/layout_cabinet.xhtml">
            <ui:define name="header">
                Редактирование категории
            </ui:define>
            <ui:define name="content">
                <h:form class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-2">Дата</label>
                        <div class="col-sm-2">
                            <h:inputText class="form-control form-control-static date" 
                                         value="#{cabinetRecords.date}">
                                <f:convertDateTime type="date" pattern="dd.MM.yyyy" />
                            </h:inputText>
                        </div>
                        <div class="col-sm-2">
                            <h:commandButton class="btn btn-primary"
                                             action="#{cabinetRecords.reload()}"
                                             value="Обновить"/>
                        </div>
                    </div>
                    <hr />
                    <ui:repeat value="#{cabinetRecords.model.valueModels}"
                               var="r">
                        <div class="form-group">
                            <h:outputLabel value="#{r.name}" class="control-label col-sm-2" />
                            <div class="col-sm-10">
                                <h:inputText class="form-control" 
                                             value="#{r.intValue}"
                                             rendered="#{r.valueType eq 'Integer'}" />
                                <h:inputText class="form-control"
                                             value="#{r.floatValue}"
                                             rendered="#{r.valueType eq 'Float'}" />
                                <h:inputTextarea class="form-control"
                                                 value="#{r.textValue}"
                                                 rendered="#{r.valueType eq 'Text'}" />
                                <h:selectOneMenu 
                                    class="form-control"
                                    rendered="#{r.valueType eq 'Enum'}"
                                    value="#{r.enumValueId}">
                                    <f:selectItem
                                        itemLabel="Не указано"
                                        itemValue="#{null}" />
                                    <f:selectItems
                                        value="#{r.enumValues}"
                                        var="ev"
                                        itemLabel="#{ev.name}"
                                        itemValue="#{ev.id}" />
                                </h:selectOneMenu>
                            </div>
                        </div>
                    </ui:repeat>
                    <div class="col-sm-offset-2 col-sm-10">
                        <h:commandButton class="btn btn-primary"
                                         action="#{cabinetRecords.update()}"
                                         value="Сохранить" />
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/cabinet/master_record_groups.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <ui:composition template="/WEB-INF/faces/layout_cabinet.xhtml">
            <ui:define name="header">
                Выбор категории записей
            </ui:define>
            <ui:define name="content">
                <h:form class="form">
                    <div class="form-group">
                        <label>Спортсмен</label>
                        <h:selectOneMenu
                            class="form-control"
                            value="#{cabinetMasterRecords.athleteId}">
                            <f:selectItems value="#{cabinetAthletes.athletes}" 
                                           var="i"
                                           itemValue="#{i.id}"
                                           itemLabel="#{i.fullFIO}"/>
                        </h:selectOneMenu>
                    </div>
                    <div class="form-group">
                        <label>Группа записей</label>
                        <h:selectOneMenu
                            class="form-control"
                            value="#{cabinetMasterRecords.groupId}">
                            <f:selectItems value="#{cabinetRecordGroups.groups}" 
                                           var="g"
                                           itemValue="#{g.id}"
                                           itemLabel="#{g.name}#{accountBean.canEdit(g.sourceType) ? '' : '(только чтение)'}"/>
                        </h:selectOneMenu>
                    </div>
                    <div class="form-group">
                        <label>Дата</label>
                        <h:inputText class="form-control date"
                                     value="#{cabinetMasterRecords.date}">
                            <f:convertDateTime pattern="dd.MM.yyyy" />
                        </h:inputText>
                    </div>
                    <h:commandButton action="#{cabinetMasterRecords.reload()}"
                                     class="btn btn-primary"
                                     value="Показать" />

                    <ui:fragment rendered="#{not empty cabinetMasterRecords.model and accountBean.canEdit(cabinetMasterRecords.model.sourceType)}">
                        <hr />
                        <ui:repeat value="#{cabinetMasterRecords.model.valueModels}"
                                   var="r">
                            <div class="form-group">
                                <h:outputLabel value="#{r.name}" />
                                <div>
                                    <h:inputText class="form-control" 
                                                 value="#{r.intValue}"
                                                 rendered="#{r.valueType eq 'Integer'}" />
                                    <h:inputText class="form-control"
                                                 value="#{r.floatValue}"
                                                 rendered="#{r.valueType eq 'Float'}" />
                                    <h:inputTextarea class="form-control"
                                                     value="#{r.textValue}"
                                                     rendered="#{r.valueType eq 'Text'}" />
                                    <h:selectOneMenu 
                                        class="form-control"
                                        rendered="#{r.valueType eq 'Enum'}"
                                        value="#{r.enumValueId}">
                                        <f:selectItem
                                            itemLabel="Не указано"
                                            itemValue="#{null}" />
                                        <f:selectItems
                                            value="#{r.enumValues}"
                                            var="ev"
                                            itemLabel="#{ev.name}"
                                            itemValue="#{ev.id}" />
                                    </h:selectOneMenu>
                                </div>
                            </div>
                        </ui:repeat>
                        <div>
                            <h:commandButton class="btn btn-primary"
                                             action="#{cabinetMasterRecords.update()}"
                                             value="Сохранить" />
                        </div>
                    </ui:fragment>
                    <ui:fragment rendered="#{not empty cabinetMasterRecords.model and not accountBean.canEdit(cabinetMasterRecords.model.sourceType)}">
                        <hr />
                        <ui:repeat value="#{cabinetMasterRecords.model.valueModels}"
                                   var="r">
                            <div>
                                <h:outputLabel value="#{r.name}" />:
                                <ui:fragment rendered="#{r.hasValue}">
                                    <h:outputText 
                                        value="#{r.intValue}"
                                        rendered="#{r.valueType eq 'Integer'}" />
                                    <h:outputText 
                                        value="#{r.floatValue}"
                                        rendered="#{r.valueType eq 'Float'}" />
                                    <h:outputText 
                                        value="#{r.textValue}"
                                        rendered="#{r.valueType eq 'Text'}" />
                                    <h:outputText
                                        value="#{r.enumValue.name}"
                                        rendered="#{r.valueType eq 'Enum'}"/>
                                </ui:fragment>
                                <ui:fragment rendered="#{not r.hasValue}">
                                    Нет значения
                                </ui:fragment>
                            </div>
                        </ui:repeat>
                    </ui:fragment>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/cabinet/masters.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <ui:composition template="/WEB-INF/faces/layout_cabinet.xhtml">
            <ui:define name="header">
                Специалисты
            </ui:define>
            <ui:define name="content">
                <div class="list-group">
                    <ui:repeat value="#{masters.masters}"
                               var="m">
                        <a href="profile_info.xhtml?id=#{m.id}" class="list-group-item">
                            <h3 style="margin-top: 0"><h:outputText value="#{m.shortFIO}" /></h3>
                            <div>
                                <h:outputText value="#{masters.getMasterTypeCaption(m)}" />
                            </div>
                        </a >
                    </ui:repeat>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/cabinet/pending_requests.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <ui:composition template="/WEB-INF/faces/layout_cabinet.xhtml">
        <ui:define name="header">Запросы</ui:define>
        <ui:define name="content">
            <ui:fragment rendered="#{pendingRequests.request == null}">
                <h3>Запросы отсутствуют</h3>
            </ui:fragment>
            <ui:fragment rendered="#{pendingRequests.request != null}">
                <div class="list-group">
                    <div class="list-group-item">
                        Запрос к #{pendingRequests.request.master.fullFIO} создан
                    </div>
                </div>
            </ui:fragment>
        </ui:define>
    </ui:composition>
</html>